[2023-06-23T22:17:04.776+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aloca.python-operator-test manual__2023-06-23T22:17:03.002316+00:00 [queued]>
[2023-06-23T22:17:04.795+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aloca.python-operator-test manual__2023-06-23T22:17:03.002316+00:00 [queued]>
[2023-06-23T22:17:04.797+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-23T22:17:04.809+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): python-operator-test> on 2023-06-23 22:17:03.002316+00:00
[2023-06-23T22:17:04.818+0000] {standard_task_runner.py:57} INFO - Started process 1061 to run task
[2023-06-23T22:17:04.822+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'aloca', 'python-operator-test', 'manual__2023-06-23T22:17:03.002316+00:00', '--job-id', '527', '--raw', '--subdir', 'DAGS_FOLDER/aloca.py', '--cfg-path', '/tmp/tmpwn5g00hd']
[2023-06-23T22:17:04.828+0000] {standard_task_runner.py:85} INFO - Job 527: Subtask python-operator-test
[2023-06-23T22:17:04.882+0000] {task_command.py:410} INFO - Running <TaskInstance: aloca.python-operator-test manual__2023-06-23T22:17:03.002316+00:00 [running]> on host 6bba1fead03c
[2023-06-23T22:17:04.948+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aloca' AIRFLOW_CTX_TASK_ID='python-operator-test' AIRFLOW_CTX_EXECUTION_DATE='2023-06-23T22:17:03.002316+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-23T22:17:03.002316+00:00'
[2023-06-23T22:17:04.960+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-06-23T22:17:04.962+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/aloca.py", line 17, in test
    print('eitaaaaa', dict(conn.get_extra()['key_path']))
                           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2023-06-23T22:17:04.976+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=aloca, task_id=python-operator-test, execution_date=20230623T221703, start_date=20230623T221704, end_date=20230623T221704
[2023-06-23T22:17:04.986+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 527 for task python-operator-test (string indices must be integers, not 'str'; 1061)
[2023-06-23T22:17:05.038+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-23T22:17:05.055+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
