[2023-06-18T14:22:45.713+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs-files-dag.delete_table scheduled__2023-06-18T14:22:19.941238+00:00 [queued]>
[2023-06-18T14:22:45.718+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs-files-dag.delete_table scheduled__2023-06-18T14:22:19.941238+00:00 [queued]>
[2023-06-18T14:22:45.719+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-18T14:22:45.727+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryDeleteTableOperator): delete_table> on 2023-06-18 14:22:19.941238+00:00
[2023-06-18T14:22:45.732+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2023-06-18T14:22:45.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs-files-dag', 'delete_table', 'scheduled__2023-06-18T14:22:19.941238+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/gcp_test.py', '--cfg-path', '/tmp/tmpkh067q37']
[2023-06-18T14:22:45.738+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask delete_table
[2023-06-18T14:22:45.795+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs-files-dag.delete_table scheduled__2023-06-18T14:22:19.941238+00:00 [running]> on host fd6b68bac112
[2023-06-18T14:22:45.886+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs-files-dag' AIRFLOW_CTX_TASK_ID='delete_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-18T14:22:19.941238+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-18T14:22:19.941238+00:00'
[2023-06-18T14:22:45.889+0000] {bigquery.py:2323} INFO - Deleting: bus-data-389717.dbt_busdata_stag.external_table_bus
[2023-06-18T14:22:45.905+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2324, in execute
    hook = BigQueryHook(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 110, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2023-06-18T14:22:45.908+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=gcs-files-dag, task_id=delete_table, execution_date=20230618T142219, start_date=20230618T142245, end_date=20230618T142245
[2023-06-18T14:22:45.916+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task delete_table (The conn_id `google_cloud_default` isn't defined; 60)
[2023-06-18T14:22:45.951+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-18T14:22:45.968+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
