[2023-06-23T22:22:53.640+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:22:53.645+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:22:53.646+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 5
[2023-06-23T22:22:53.652+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): clean-gcp-files> on 2023-06-23 22:20:13.759773+00:00
[2023-06-23T22:22:53.657+0000] {standard_task_runner.py:57} INFO - Started process 1216 to run task
[2023-06-23T22:22:53.660+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'running-buses-clean-files-dag', 'clean-gcp-files', 'manual__2023-06-23T22:20:13.759773+00:00', '--job-id', '539', '--raw', '--subdir', 'DAGS_FOLDER/running_buses_clean_files.py', '--cfg-path', '/tmp/tmpso_xmtie']
[2023-06-23T22:22:53.663+0000] {standard_task_runner.py:85} INFO - Job 539: Subtask clean-gcp-files
[2023-06-23T22:22:53.703+0000] {task_command.py:410} INFO - Running <TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [running]> on host 6bba1fead03c
[2023-06-23T22:22:53.761+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='running-buses-clean-files-dag' AIRFLOW_CTX_TASK_ID='clean-gcp-files' AIRFLOW_CTX_EXECUTION_DATE='2023-06-23T22:20:13.759773+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-23T22:20:13.759773+00:00'
[2023-06-23T22:22:53.764+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvfdo4eghd --system-site-packages
[2023-06-23T22:22:53.767+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:22:54.538+0000] {process_utils.py:189} INFO - created virtual environment CPython3.11.4.final.0-64 in 376ms
[2023-06-23T22:22:54.540+0000] {process_utils.py:189} INFO -   creator CPython3Posix(dest=/tmp/venvfdo4eghd, clear=False, no_vcs_ignore=False, global=True)
[2023-06-23T22:22:54.541+0000] {process_utils.py:189} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-06-23T22:22:54.541+0000] {process_utils.py:189} INFO -     added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
[2023-06-23T22:22:54.542+0000] {process_utils.py:189} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-06-23T22:22:54.559+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venvfdo4eghd/bin/pip install -r /tmp/venvfdo4eghd/requirements.txt
[2023-06-23T22:22:54.560+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:22:55.940+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-cloud-storage in /home/***/.local/lib/python3.11/site-packages (from -r /tmp/venvfdo4eghd/requirements.txt (line 1)) (2.9.0)
[2023-06-23T22:22:55.944+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (2.20.0)
[2023-06-23T22:22:55.945+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (2.11.0)
[2023-06-23T22:22:55.946+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (2.3.2)
[2023-06-23T22:22:55.947+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-resumable-media>=2.3.2 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (2.5.0)
[2023-06-23T22:22:55.948+0000] {process_utils.py:189} INFO - Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (2.31.0)
[2023-06-23T22:22:55.954+0000] {process_utils.py:189} INFO - Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /home/***/.local/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (1.59.1)
[2023-06-23T22:22:55.955+0000] {process_utils.py:189} INFO - Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /home/***/.local/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (4.23.2)
[2023-06-23T22:22:55.961+0000] {process_utils.py:189} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (5.3.1)
[2023-06-23T22:22:55.962+0000] {process_utils.py:189} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (0.2.8)
[2023-06-23T22:22:55.963+0000] {process_utils.py:189} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (4.9)
[2023-06-23T22:22:55.963+0000] {process_utils.py:189} INFO - Requirement already satisfied: six>=1.9.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (1.16.0)
[2023-06-23T22:22:55.964+0000] {process_utils.py:189} INFO - Requirement already satisfied: urllib3<2.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (1.26.16)
[2023-06-23T22:22:55.971+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/***/.local/lib/python3.11/site-packages (from google-resumable-media>=2.3.2->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (1.5.0)
[2023-06-23T22:22:55.976+0000] {process_utils.py:189} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (3.1.0)
[2023-06-23T22:22:55.977+0000] {process_utils.py:189} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (3.4)
[2023-06-23T22:22:55.978+0000] {process_utils.py:189} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (2023.5.7)
[2023-06-23T22:22:56.013+0000] {process_utils.py:189} INFO - Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/***/.local/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvfdo4eghd/requirements.txt (line 1)) (0.4.8)
[2023-06-23T22:22:58.135+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venvfdo4eghd/bin/python /tmp/venvfdo4eghd/script.py /tmp/venvfdo4eghd/script.in /tmp/venvfdo4eghd/script.out /tmp/venvfdo4eghd/string_args.txt
[2023-06-23T22:22:58.138+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:23:00.844+0000] {process_utils.py:189} INFO - [[34m2023-06-23T22:23:00.840+0000[0m] {[34mbase.py:[0m73} INFO[0m - Using connection ID 'google_cloud_default' for task execution.[0m
[2023-06-23T22:23:01.814+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-23T22:23:01.834+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=running-buses-clean-files-dag, task_id=clean-gcp-files, execution_date=20230623T222013, start_date=20230623T222253, end_date=20230623T222301
[2023-06-23T22:23:01.902+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-23T22:23:01.921+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
