[2023-06-23T22:21:10.499+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:21:10.505+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:21:10.506+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-06-23T22:21:10.512+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): clean-gcp-files> on 2023-06-23 22:20:13.759773+00:00
[2023-06-23T22:21:10.519+0000] {standard_task_runner.py:57} INFO - Started process 1153 to run task
[2023-06-23T22:21:10.524+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'running-buses-clean-files-dag', 'clean-gcp-files', 'manual__2023-06-23T22:20:13.759773+00:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/running_buses_clean_files.py', '--cfg-path', '/tmp/tmppnrykvgh']
[2023-06-23T22:21:10.528+0000] {standard_task_runner.py:85} INFO - Job 536: Subtask clean-gcp-files
[2023-06-23T22:21:10.581+0000] {task_command.py:410} INFO - Running <TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [running]> on host 6bba1fead03c
[2023-06-23T22:21:10.650+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='running-buses-clean-files-dag' AIRFLOW_CTX_TASK_ID='clean-gcp-files' AIRFLOW_CTX_EXECUTION_DATE='2023-06-23T22:20:13.759773+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-23T22:20:13.759773+00:00'
[2023-06-23T22:21:10.653+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvvehcvra3 --system-site-packages
[2023-06-23T22:21:10.655+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:21:11.495+0000] {process_utils.py:189} INFO - created virtual environment CPython3.11.4.final.0-64 in 465ms
[2023-06-23T22:21:11.497+0000] {process_utils.py:189} INFO -   creator CPython3Posix(dest=/tmp/venvvehcvra3, clear=False, no_vcs_ignore=False, global=True)
[2023-06-23T22:21:11.498+0000] {process_utils.py:189} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-06-23T22:21:11.499+0000] {process_utils.py:189} INFO -     added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
[2023-06-23T22:21:11.499+0000] {process_utils.py:189} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-06-23T22:21:11.511+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venvvehcvra3/bin/pip install -r /tmp/venvvehcvra3/requirements.txt
[2023-06-23T22:21:11.513+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:21:12.811+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-cloud-storage in /home/***/.local/lib/python3.11/site-packages (from -r /tmp/venvvehcvra3/requirements.txt (line 1)) (2.9.0)
[2023-06-23T22:21:12.816+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (2.20.0)
[2023-06-23T22:21:12.817+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (2.11.0)
[2023-06-23T22:21:12.817+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (2.3.2)
[2023-06-23T22:21:12.818+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-resumable-media>=2.3.2 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (2.5.0)
[2023-06-23T22:21:12.819+0000] {process_utils.py:189} INFO - Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (2.31.0)
[2023-06-23T22:21:12.825+0000] {process_utils.py:189} INFO - Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /home/***/.local/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (1.59.1)
[2023-06-23T22:21:12.826+0000] {process_utils.py:189} INFO - Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /home/***/.local/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (4.23.2)
[2023-06-23T22:21:12.832+0000] {process_utils.py:189} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (5.3.1)
[2023-06-23T22:21:12.833+0000] {process_utils.py:189} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (0.2.8)
[2023-06-23T22:21:12.833+0000] {process_utils.py:189} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (4.9)
[2023-06-23T22:21:12.834+0000] {process_utils.py:189} INFO - Requirement already satisfied: six>=1.9.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (1.16.0)
[2023-06-23T22:21:12.835+0000] {process_utils.py:189} INFO - Requirement already satisfied: urllib3<2.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (1.26.16)
[2023-06-23T22:21:12.841+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/***/.local/lib/python3.11/site-packages (from google-resumable-media>=2.3.2->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (1.5.0)
[2023-06-23T22:21:12.848+0000] {process_utils.py:189} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (3.1.0)
[2023-06-23T22:21:12.848+0000] {process_utils.py:189} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (3.4)
[2023-06-23T22:21:12.850+0000] {process_utils.py:189} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (2023.5.7)
[2023-06-23T22:21:12.884+0000] {process_utils.py:189} INFO - Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/***/.local/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvvehcvra3/requirements.txt (line 1)) (0.4.8)
[2023-06-23T22:21:14.790+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venvvehcvra3/bin/python /tmp/venvvehcvra3/script.py /tmp/venvvehcvra3/script.in /tmp/venvvehcvra3/script.out /tmp/venvvehcvra3/string_args.txt
[2023-06-23T22:21:14.792+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:21:15.657+0000] {process_utils.py:189} INFO - Traceback (most recent call last):
[2023-06-23T22:21:15.658+0000] {process_utils.py:189} INFO -   File "/tmp/venvvehcvra3/script.py", line 45, in <module>
[2023-06-23T22:21:15.658+0000] {process_utils.py:189} INFO -     res = clean_files(*arg_dict["args"], **arg_dict["kwargs"])
[2023-06-23T22:21:15.659+0000] {process_utils.py:189} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-23T22:21:15.660+0000] {process_utils.py:189} INFO -   File "/tmp/venvvehcvra3/script.py", line 28, in clean_files
[2023-06-23T22:21:15.660+0000] {process_utils.py:189} INFO -     conn = BaseHook.get_connection('google_cloud_default')
[2023-06-23T22:21:15.661+0000] {process_utils.py:189} INFO -            ^^^^^^^^
[2023-06-23T22:21:15.661+0000] {process_utils.py:189} INFO - NameError: name 'BaseHook' is not defined
[2023-06-23T22:21:15.762+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 578, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 428, in _execute_python_callable_in_subprocess
    execute_in_subprocess(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvvehcvra3/bin/python', '/tmp/venvvehcvra3/script.py', '/tmp/venvvehcvra3/script.in', '/tmp/venvvehcvra3/script.out', '/tmp/venvvehcvra3/string_args.txt']' returned non-zero exit status 1.
[2023-06-23T22:21:15.774+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=running-buses-clean-files-dag, task_id=clean-gcp-files, execution_date=20230623T222013, start_date=20230623T222110, end_date=20230623T222115
[2023-06-23T22:21:15.783+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 536 for task clean-gcp-files (Command '['/tmp/venvvehcvra3/bin/python', '/tmp/venvvehcvra3/script.py', '/tmp/venvvehcvra3/script.in', '/tmp/venvvehcvra3/script.out', '/tmp/venvvehcvra3/string_args.txt']' returned non-zero exit status 1.; 1153)
[2023-06-23T22:21:15.837+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-23T22:21:15.853+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
