[2023-06-17T19:05:15.003+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dbt-dag.dbt_run scheduled__2023-06-17T19:05:06.738865+00:00 [queued]>
[2023-06-17T19:05:15.010+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dbt-dag.dbt_run scheduled__2023-06-17T19:05:06.738865+00:00 [queued]>
[2023-06-17T19:05:15.010+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T19:05:15.011+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-06-17T19:05:15.011+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-17T19:05:15.021+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2023-06-17 19:05:06.738865+00:00
[2023-06-17T19:05:15.026+0000] {standard_task_runner.py:55} INFO - Started process 89 to run task
[2023-06-17T19:05:15.030+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt-dag', 'dbt_run', 'scheduled__2023-06-17T19:05:06.738865+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_test.py', '--cfg-path', '/tmp/tmpk38zi5d0']
[2023-06-17T19:05:15.030+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask dbt_run
[2023-06-17T19:05:15.087+0000] {task_command.py:388} INFO - Running <TaskInstance: dbt-dag.dbt_run scheduled__2023-06-17T19:05:06.738865+00:00 [running]> on host d15b10d50d8d
[2023-06-17T19:05:15.141+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt-dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T19:05:06.738865+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-17T19:05:06.738865+00:00
[2023-06-17T19:05:15.142+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/***/tmp_data/dbt_bus_data/.dbt_profile
[2023-06-17T19:05:15.150+0000] {dbt_hook.py:126} INFO - Output:
[2023-06-17T19:05:16.709+0000] {dbt_hook.py:130} INFO - 19:05:16  Error importing adapter: No module named 'dbt.adapters.bigquery'
[2023-06-17T19:05:16.710+0000] {dbt_hook.py:130} INFO - 19:05:16  Encountered an error while reading profiles:
[2023-06-17T19:05:16.710+0000] {dbt_hook.py:130} INFO -   ERROR: Runtime Error
[2023-06-17T19:05:16.711+0000] {dbt_hook.py:130} INFO -   Credentials in profile "dbt_bus_data", target "dev" invalid: Runtime Error
[2023-06-17T19:05:16.711+0000] {dbt_hook.py:130} INFO -     Could not find adapter type bigquery!Defined profiles:
[2023-06-17T19:05:16.711+0000] {dbt_hook.py:130} INFO -  - dbt_bus_data
[2023-06-17T19:05:16.712+0000] {dbt_hook.py:130} INFO - For more information on configuring profiles, please consult the dbt docs:
[2023-06-17T19:05:16.712+0000] {dbt_hook.py:130} INFO - 
[2023-06-17T19:05:16.713+0000] {dbt_hook.py:130} INFO - https://docs.getdbt.com/docs/configure-your-profile
[2023-06-17T19:05:16.713+0000] {dbt_hook.py:130} INFO - 
[2023-06-17T19:05:16.714+0000] {dbt_hook.py:130} INFO - 19:05:16  Encountered an error:
[2023-06-17T19:05:16.714+0000] {dbt_hook.py:130} INFO - Runtime Error
[2023-06-17T19:05:16.715+0000] {dbt_hook.py:130} INFO -   Could not run dbt
[2023-06-17T19:05:16.828+0000] {dbt_hook.py:134} INFO - Command exited with return code 2
[2023-06-17T19:05:16.840+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2023-06-17T19:05:16.843+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dbt-dag, task_id=dbt_run, execution_date=20230617T190506, start_date=20230617T190515, end_date=20230617T190516
[2023-06-17T19:05:16.853+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task dbt_run (dbt command failed; 89)
[2023-06-17T19:05:16.879+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-17T19:05:16.895+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
