[2023-06-17T17:06:35.949+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt-dag.dbt_run manual__2023-06-17T17:02:41.638909+00:00 [queued]>
[2023-06-17T17:06:35.956+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt-dag.dbt_run manual__2023-06-17T17:02:41.638909+00:00 [queued]>
[2023-06-17T17:06:35.956+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 3
[2023-06-17T17:06:35.966+0000] {taskinstance.py:1327} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2023-06-17 17:02:41.638909+00:00
[2023-06-17T17:06:35.972+0000] {standard_task_runner.py:57} INFO - Started process 467 to run task
[2023-06-17T17:06:35.977+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt-dag', 'dbt_run', 'manual__2023-06-17T17:02:41.638909+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dbt_test.py', '--cfg-path', '/tmp/tmp02jltygd']
[2023-06-17T17:06:35.980+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask dbt_run
[2023-06-17T17:06:36.031+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt-dag.dbt_run manual__2023-06-17T17:02:41.638909+00:00 [running]> on host 521d1a52fc3d
[2023-06-17T17:06:36.092+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt-dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-06-17T17:02:41.638909+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-17T17:02:41.638909+00:00'
[2023-06-17T17:06:36.094+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/***/tmp_data/dbt_bus_data/.dbt_profile
[2023-06-17T17:06:36.105+0000] {dbt_hook.py:126} INFO - Output:
[2023-06-17T17:06:38.034+0000] {dbt_hook.py:130} INFO - [0m17:06:38  Running with dbt=1.5.1
[2023-06-17T17:06:38.522+0000] {dbt_hook.py:130} INFO - [0m17:06:38  Encountered an error:
[2023-06-17T17:06:38.523+0000] {dbt_hook.py:130} INFO - Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
[2023-06-17T17:06:38.528+0000] {dbt_hook.py:130} INFO - [0m17:06:38  Traceback (most recent call last):
[2023-06-17T17:06:38.529+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper
[2023-06-17T17:06:38.529+0000] {dbt_hook.py:130} INFO -     result, success = func(*args, **kwargs)
[2023-06-17T17:06:38.530+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper
[2023-06-17T17:06:38.530+0000] {dbt_hook.py:130} INFO -     return func(*args, **kwargs)
[2023-06-17T17:06:38.531+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper
[2023-06-17T17:06:38.531+0000] {dbt_hook.py:130} INFO -     profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)
[2023-06-17T17:06:38.532+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile
[2023-06-17T17:06:38.532+0000] {dbt_hook.py:130} INFO -     profile_renderer, profile_name, profile_name_override, target_override, threads_override
[2023-06-17T17:06:38.533+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render
[2023-06-17T17:06:38.533+0000] {dbt_hook.py:130} INFO -     threads_override=threads_override,
[2023-06-17T17:06:38.534+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles
[2023-06-17T17:06:38.534+0000] {dbt_hook.py:130} INFO -     threads_override=threads_override,
[2023-06-17T17:06:38.535+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info
[2023-06-17T17:06:38.535+0000] {dbt_hook.py:130} INFO -     profile_data, profile_name, target_name
[2023-06-17T17:06:38.535+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile
[2023-06-17T17:06:38.536+0000] {dbt_hook.py:130} INFO -     cls = load_plugin(typename)
[2023-06-17T17:06:38.536+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 202, in load_plugin
[2023-06-17T17:06:38.537+0000] {dbt_hook.py:130} INFO -     return FACTORY.load_plugin(name)
[2023-06-17T17:06:38.537+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 57, in load_plugin
[2023-06-17T17:06:38.538+0000] {dbt_hook.py:130} INFO -     mod: Any = import_module("." + name, "dbt.adapters")
[2023-06-17T17:06:38.538+0000] {dbt_hook.py:130} INFO -   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[2023-06-17T17:06:38.539+0000] {dbt_hook.py:130} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2023-06-17T17:06:38.539+0000] {dbt_hook.py:130} INFO -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[2023-06-17T17:06:38.539+0000] {dbt_hook.py:130} INFO -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[2023-06-17T17:06:38.540+0000] {dbt_hook.py:130} INFO -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[2023-06-17T17:06:38.540+0000] {dbt_hook.py:130} INFO -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[2023-06-17T17:06:38.541+0000] {dbt_hook.py:130} INFO -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[2023-06-17T17:06:38.542+0000] {dbt_hook.py:130} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2023-06-17T17:06:38.542+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 1, in <module>
[2023-06-17T17:06:38.543+0000] {dbt_hook.py:130} INFO -     from dbt.adapters.bigquery.connections import BigQueryConnectionManager  # noqa
[2023-06-17T17:06:38.543+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/connections.py", line 14, in <module>
[2023-06-17T17:06:38.544+0000] {dbt_hook.py:130} INFO -     import google.cloud.bigquery
[2023-06-17T17:06:38.544+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
[2023-06-17T17:06:38.545+0000] {dbt_hook.py:130} INFO -     from google.cloud.bigquery.client import Client
[2023-06-17T17:06:38.545+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 76, in <module>
[2023-06-17T17:06:38.546+0000] {dbt_hook.py:130} INFO -     from google.cloud.bigquery import _job_helpers
[2023-06-17T17:06:38.546+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/_job_helpers.py", line 24, in <module>
[2023-06-17T17:06:38.547+0000] {dbt_hook.py:130} INFO -     from google.cloud.bigquery import job
[2023-06-17T17:06:38.547+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/__init__.py", line 27, in <module>
[2023-06-17T17:06:38.548+0000] {dbt_hook.py:130} INFO -     from google.cloud.bigquery.job.copy_ import CopyJob
[2023-06-17T17:06:38.548+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/copy_.py", line 22, in <module>
[2023-06-17T17:06:38.549+0000] {dbt_hook.py:130} INFO -     from google.cloud.bigquery.table import TableReference
[2023-06-17T17:06:38.550+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 51, in <module>
[2023-06-17T17:06:38.550+0000] {dbt_hook.py:130} INFO -     from shapely import wkt  # type: ignore
[2023-06-17T17:06:38.551+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/shapely/wkt.py", line 6, in <module>
[2023-06-17T17:06:38.552+0000] {dbt_hook.py:130} INFO -     from shapely import geos
[2023-06-17T17:06:38.552+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/shapely/geos.py", line 100, in <module>
[2023-06-17T17:06:38.553+0000] {dbt_hook.py:130} INFO -     _lgeos = load_dll('geos_c', fallbacks=alt_paths)
[2023-06-17T17:06:38.553+0000] {dbt_hook.py:130} INFO -   File "/home/***/.local/lib/python3.7/site-packages/shapely/geos.py", line 56, in load_dll
[2023-06-17T17:06:38.554+0000] {dbt_hook.py:130} INFO -     libname, fallbacks or []))
[2023-06-17T17:06:38.555+0000] {dbt_hook.py:130} INFO - OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
[2023-06-17T17:06:38.555+0000] {dbt_hook.py:130} INFO - 
[2023-06-17T17:06:39.568+0000] {dbt_hook.py:134} INFO - Command exited with return code 2
[2023-06-17T17:06:39.582+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2023-06-17T17:06:39.586+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt-dag, task_id=dbt_run, execution_date=20230617T170241, start_date=20230617T170635, end_date=20230617T170639
[2023-06-17T17:06:39.597+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 14 for task dbt_run (dbt command failed; 467)
[2023-06-17T17:06:39.620+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-17T17:06:39.638+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
