[2023-06-15T18:41:06.780+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs-files-dag.create_external_table manual__2023-06-15T18:41:04.605495+00:00 [queued]>
[2023-06-15T18:41:06.787+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs-files-dag.create_external_table manual__2023-06-15T18:41:04.605495+00:00 [queued]>
[2023-06-15T18:41:06.788+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-15T18:41:06.797+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryCreateExternalTableOperator): create_external_table> on 2023-06-15 18:41:04.605495+00:00
[2023-06-15T18:41:06.802+0000] {standard_task_runner.py:57} INFO - Started process 4832 to run task
[2023-06-15T18:41:06.807+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs-files-dag', 'create_external_table', 'manual__2023-06-15T18:41:04.605495+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/gcp_test.py', '--cfg-path', '/tmp/tmphci2tnif']
[2023-06-15T18:41:06.808+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask create_external_table
[2023-06-15T18:41:06.864+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs-files-dag.create_external_table manual__2023-06-15T18:41:04.605495+00:00 [running]> on host 6f3c5cb11aa3
[2023-06-15T18:41:06.936+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs-files-dag' AIRFLOW_CTX_TASK_ID='create_external_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T18:41:04.605495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T18:41:04.605495+00:00'
[2023-06-15T18:41:06.952+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-06-15T18:41:07.737+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1667, in execute
    table_resource=table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 407, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/bus-data-389717/datasets/dbt_busdata_stag/tables?prettyPrint=false: CsvOptions can only be specified if storage format is CSV.
[2023-06-15T18:41:07.755+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=gcs-files-dag, task_id=create_external_table, execution_date=20230615T184104, start_date=20230615T184106, end_date=20230615T184107
[2023-06-15T18:41:07.778+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 54 for task create_external_table (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/bus-data-389717/datasets/dbt_busdata_stag/tables?prettyPrint=false: CsvOptions can only be specified if storage format is CSV.; 4832)
[2023-06-15T18:41:07.818+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T18:41:07.836+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
